### ISSUE TITLE
ModuleNotFoundError after fresh installation

### ISSUE THREAD

**Issue by DrMint** [MatthiasValvekens/pyHanko#11]
**Describe the bug**
After installing pyHanko on my machine, it's impossible to run it without getting this error:

`ModuleNotFoundError: No module named 'pyhanko.sign.ades'`

**To Reproduce**
1. pip3 install pyHanko
2. pyhanko

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (WSL)
- Python: 3.8.5

**Additional context**
I also tried to do apt-get update/upgrade, it didn't help.
I've added the entire log from the installation and the traceback when running pyhanko
[log.txt](https://github.com/MatthiasValvekens/pyHanko/files/6199374/log.txt)

**Comment by MatthiasValvekens** [comment]
My apologies! That's probably a packaging error; I must have forgotten to declare the new `pyhanko.sign.ades` package in my `setup.py` file in the latest realease... Rookie mistake; I'll fix it and do a patch release.

**Comment by MatthiasValvekens** [comment]
Done, I yanked 0.5.0 from PyPI and pushed a new release with version number 0.5.1 that should fix the packaging error (I just tried a fresh install on my machine). You may have to run `pip install pyHanko==0.5.1` to force pip to download the new release from PyPI.

That was embarrassing, sorry for your trouble. I've made a note in my release checklist to double-check this sort of thing before publishing...

**Comment by DrMint** [comment]
No problem :) It's working now, thanks for the quick fix!
