### ISSUE TITLE
TextBoxStyle returns ''NoneType' object is not iterable' when the stamp contains an empty line

### ISSUE THREAD

**Issue by ilpadrinohack** [MatthiasValvekens/pyHanko#132]
I am trying to  sign a pdf using a pkcs12 file: All it is ok (although the stamp text font is too small and cannot make it bigger), except if I try to specify a font type in the TextBoxStyle. This did not happen in the old version oh PyHanko. I have upgraded my computer and all pythons modules (now I am working with pyHanko 0.13.2)  and now it does not work. This is the code:

`from dataclasses import fields
from distutils import text_file
from functools import partial
from io import BytesIO
from os import name
from struct import pack
from PyKCS11.LowLevel import CKA_SUBJECT, CKA_VALUE
from pkcs11 import Attribute, ObjectClass
from pyhanko.pdf_utils import text
from pyhanko.pdf_utils.images import PdfImage
from tkinter import messagebox
from tkinter import *
from pyhanko.pdf_utils.font.opentype import GlyphAccumulator, GlyphAccumulatorFactory
from pyhanko.pdf_utils import font, writer,text,images
from pyhanko.pdf_utils.text import TextBoxStyle
from pyhanko.pdf_utils.font import  SimpleFontEngine
from pyhanko.sign.fields import SigCertConstraints, SigSeedSubFilter
from pyhanko.sign import fields
from pyhanko.stamp import STAMP_ART_CONTENT, BaseStamp
from pyhanko.stamp import TextStamp,TextStampStyle

import logging
from pyhanko import stamp
from pkcs11 import PKCS11Error
from pyhanko.pdf_utils.incremental_writer import IncrementalPdfFileWriter
from PyPDF2 import PdfFileReader
from pyhanko.sign import signers, pkcs11,timestamps
from pyhanko_certvalidator import ValidationContext

from datetime import datetime
from pyhanko.sign.general import load_cert_from_pemder
from tlslite import X509 as XX509
import OpenSSL
from OpenSSL import crypto
from OpenSSL.crypto import FILETYPE_ASN1,FILETYPE_PEM, dump_certificate, load_certificate
from PyKCS11 import *
from cryptography.hazmat.primitives  import *
from tkinter import simpledialog
import tkinter as tk
from tkinter import filedialog,messagebox
from tkinter import *
from PIL import Image,ImageTk
from pdf2image import convert_from_path
import tkinter.font as font
from functools import partial
from pyhanko.pdf_utils.font import opentype
from cryptography.hazmat.primitives.serialization import pkcs12`

    

top1=Toplevel()
def read_all(fname):
        with open(fname, 'rb') as f:
            read_all.ci=False
            return f.read()
      
def certificadodigper():
        MINIMAL=read_all('lorem_field.pdf')
        fileopened='lorem_field.pdf'
        try:  
            top1.filename =  filedialog.askopenfilename(initialdir = ".",title = "Seleccione archivo",filetypes = (("p12 files","*.p12"),("all     files","*.*")))
            finame=top1.filename
            pin=simpledialog.askstring(title = 'Introduzca PIN', prompt='PIN secreto', show ='*')``
`
         
            FROM_CA_PKCS12 = signers.SimpleSigner.load_pkcs12(finame, passphrase=bytes(pin,'utf-8'))

            p12 = crypto.load_pkcs12(open(finame, 'rb').read(), bytes(pin,'utf-8'))
            w = IncrementalPdfFileWriter(BytesIO(MINIMAL))

            acert=p12.get_certificate()     # (signed) certificate object
            bkey=p12.get_privatekey()      # private key.
            cinter=p12.get_ca_certificates() # ca chain.   

            certs =crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, acert)
            certt2=crypto.load_certificate(FILETYPE_PEM,certs)
            subject=certt2.get_subject()
            print(subject)

            nombre = dict(subject.get_components())[b'CN'].decode()
            cif = dict(subject.get_components())[b'serialNumber'].decode()
            #empresa=dict(subject.get_components())[b'O'].decode()
            privkey=crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, bkey)
            datos_firma=f'Firma digital por:\n\n{nombre}.\n\nDNI/CIF:{cif}\n'
            print(datos_firma)
            sv = fields.SigSeedValueSpec(
                    reasons=[],            
                    flags=3,
                    )

            NOTO_SANS = f'NotoSans-Regular.ttf'
            letra=GlyphAccumulatorFactory(NOTO_SANS,font_size=10)
            print(letra)
            sp = fields.SigFieldSpec('Sigdigp', seed_value_dict=sv, on_page=0, box=(100, 100, 200, 200),)
            
            #tbst=TextBoxStyle(letra)
            tbst=text.TextBoxStyle(border_width=0)
            vc = ValidationContext(trust_roots=[FROM_CA_PKCS12.signing_cert])    
            if (read_all.ci==False):
                style=TextStampStyle(text_box_style=tbst, stamp_text=datos_firma)
            #else:    
                #style=TextStampStyle(text_box_style=tbst,stamp_text=datos_firma, background=PdfImage(cargaimagen.imname),border_width=0,background_opacity=0.4)
                #style=TextStampStyle(text_box_style=tbst,stamp_text=datos_firma,border_width=0)
            fileopened = fileopened.replace('.pdf', '-f.pdf')
            
            with open(fileopened, 'wb') as outf:
                print("llega 1")
                #out = signers.sign_pdf(w, signers.PdfSignatureMetadata(field_name='Sigdigp',reason='Firma',
                #                                    location='', 
                #                                    use_pades_lta=True,
                #                                    subfilter=fields.SigSeedSubFilter.PADES,
                #                                    embed_validation_info=True,
                #                                    validation_context=vc),new_field_spec=sp, signer=FROM_CA_PKCS12,output=outf)
                out= signers.PdfSigner(signature_meta=signers.PdfSignatureMetadata(field_name='Sigdigp',reason='Firma',
                                                   location='', 
                                                   use_pades_lta=True,
                                                   subfilter=fields.SigSeedSubFilter.PADES,
                                                   embed_validation_info=True,
                                                   validation_context=vc),signer=FROM_CA_PKCS12, new_field_spec=sp, stamp_style=style).sign_pdf(w, output=outf)

            print(nombre,cif)  
            

            

        except TypeError as e:
                        print(e)
                        salidaerror=messagebox.askokcancel("ERROR!!!!","Ha habido un error en la firma\n Aségurese de que el fichero es el correcto y la clave es la correcta")
                        if salidaerror==True:
                            top1.destroy()
        else:
                        salida=messagebox.askokcancel("Fichero firmado","Se ha realizado la firma correctamente\n Se ha guardado el archivo con el mismo nombre + la 'f'")
                        if salida==True:
                            
                            top1.destroy()  
certificadodigper()
top1.mainloop()`

I have tryed several things as:
 `NOTO_SANS = f'NotoSans-Regular.ttf'
            letra=GlyphAccumulatorFactory(NOTO_SANS,font_size=10)
            tbst=TextBoxStyle(letra)`
But always when I put some fonts, it gives 'NoneType' object is not iterable.

if  `TextBoxStyle(border_width=0)` then it works

Also I have copied some of the examples from the official GItHub Code with no success as:

`with open(NOTO_SERIF_JP, 'rb') as ffile:`
                 ` ga = GlyphAccumulator(w, ffile, font_size=10)`

Thanks in advance

**Comment by MatthiasValvekens** [comment]
Hi @ilpadrinohack,


Could you post a stack trace? This type of issue is very hard to diagnose without knowing exactly where the error's being thrown. So far it's hard to tell whether or not this is a regression, but it's fairly safe to say that pyHanko should probably throw a more helpful error message...


Also, note that `GlyphAccumulatorFactory` will look in the current working directory when you specify the path to the font file using only the file name. In particular, that means that you'll get different results depending on where you're calling the program from. :)

**Comment by ilpadrinohack** [comment]
Hi Matthias:
Regarding `GlyphAccumulatorFactory`, I am running the code in the same directory where the font files are in. Could you tell me how to do a more verbose debug in pyHanko?? 

Thanks

**Comment by ilpadrinohack** [comment]
Well, I have got a deeper debug:

`GlyphAccumulatorFactory(font_file='NotoSans-Regular.ttf', font_size=10, ot_script_tag=None, ot_language_tag=None, writing_direction=None, create_objstream_if_needed=True)` 

`Validation/revocation info will be embedded, but fetching is not allowed. This may give rise to unexpected results.`

 `Traceback (most recent call last):`

  `File "/root/Descargas/programacion/firma_digital/pades_sign/ff/test_sueltos.py", line 114, in certificadodigper
    out= signers.PdfSigner(signature_meta=signers.PdfSignatureMetadata(field_name='Sigdigp',reason='Firma',`
 ` File "/usr/local/lib/python3.10/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1241, in sign_pdf
    result = asyncio.run(`
  `File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)`
  `File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1299, in async_sign_pdf
    tbs_document = signing_session.prepare_tbs_document(`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/sign/signers/pdf_signer.py", line 1890, in prepare_tbs_document
    self.cms_writer.send(SigObjSetup(`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/sign/signers/cms_embedder.py", line 455, in write_cms
    appearance_setup.apply(sig_annot, writer)`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/sign/signers/cms_embedder.py", line 248, in apply
    sig_annot['/AP'] = stamp.as_appearances().as_pdf_object()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/stamp.py", line 523, in as_appearances
    stamp_ref = self.register()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/stamp.py", line 474, in register
    form_xobj = self.as_form_xobject()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/pdf_utils/content.py", line 231, in as_form_xobject
    command_stream = self.render()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/stamp.py", line 440, in render
    inner_content = self._render_inner_content()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/stamp.py", line 604, in _render_inner_content
    = self._inner_layout_natural_size()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/stamp.py", line 591, in _inner_layout_natural_size
    text_commands = self._text_layout()`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/stamp.py", line 583, in _text_layout
    tb.content = text`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/pdf_utils/text.py", line 163, in content
    wrapped_line, extent = self.put_string_line(line)`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/pdf_utils/text.py", line 105, in put_string_line
    shape_result = font_engine.shape(txt)`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/pdf_utils/font/opentype.py", line 449, in shape
    text_ops, (total_x, total_y) = _format_cid_glyphline_from_buffer(`
  `File "/usr/local/lib/python3.10/site-packages/pyhanko/pdf_utils/font/opentype.py", line 93, in _format_cid_glyphline_from_buffer
    no_complex_positioning = not vertical and all(`
`TypeError: 'NoneType' object is not iterable`

 Hope this can help a little bit more

Thanks
Regards

**Comment by MatthiasValvekens** [comment]
Yeah, the thing that's `None` here is a variable that's supposed to be set by HarfBuzz, not pyHanko... Which `uharfbuzz` version do you have installed?

**Comment by ilpadrinohack** [comment]
This one.

Name: uharfbuzz

**Version: 0.25.0**
Summary: Streamlined Cython bindings for the harfbuzz shaping engine
Home-page: https://github.com/trufont/uharfbuzz
Author: Adrien Tétar
Author-email: adri-from-59@hotmail.fr
License: Apache License 2.0
Location: /usr/local/lib64/python3.10/site-packages

**Comment by ilpadrinohack** [comment]
Have upgraded to uharfbuzz-0.29.0 and same results

**Comment by MatthiasValvekens** [comment]
Hi, sorry for taking so long to reply. `0.25.0` is the version specified in pyHanko's manifest (and hence also what the test suite uses). I've manually checked that [the layout tests](https://github.com/MatthiasValvekens/pyHanko/blob/master/pyhanko_tests/test_stamp.py) still pass with `0.29.0`.

Based on those facts, I think there are two possibilities: either there's an error in your code (which is not being dealt with gracefully), or there's some sort of platform dependency issue with the native components in `uharfbuzz`.

Can you confirm whether you can run the stamp layout tests I linked above? Running this in the project root should work once you have all the dependencies in place:

```
 python -m pytest pyhanko_tests/test_stamp.py
```

(note: you'll also need some external tools & set env vars to run a portion of the tests, see [here](https://github.com/MatthiasValvekens/pyHanko/blob/306958873c59c34ce828b88343e917165ccd8b11/.github/workflows/pytest-multiver.yml#L23-L35))

**Comment by ilpadrinohack** [comment]
Hi Matthias:

First thank you for taking your time looking for a solution for me,

Well, after ` python -m pytest pyhanko_tests/test_stamp.py`

I get this:

    `============================= test session starts ==============================
     platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
     rootdir: /usr/local/lib/python3.10/site-packages/pyhanko
     collected 23 items                                                             

     pyhanko_tests/test_stamp.py ....ssssssFssssss.....s                      [100%]

     =================================== FAILURES ===================================
     _________________________ test_fancy_qr_stamp ______________________________

    def test_fancy_qr_stamp():
        w = empty_page()
    >       style = QRStampStyle(
            stamp_text='Test stamp text\nAnother line of text',
            qr_inner_content=STAMP_ART_CONTENT,
        )
     E       TypeError: QRStampStyle.__init__() got an unexpected keyword argument 'qr_inner_content'

      pyhanko_tests/test_stamp.py:177: TypeError
      =========================== short test summary info ============================
       FAILED pyhanko_tests/test_stamp.py::test_fancy_qr_stamp - TypeError: QRStampS...
       =================== 1 failed, 9 passed, 13 skipped in 0.84s ====================
`

Nevertheless, I have solved it using SimpleFontEngineFactory instead of GlyphFontEngineFactory as follow:

           `letra=SimpleFontEngineFactory('Arial-BoldMT.ttf',avg_width=0.5)  
            tbst=TextBoxStyle(letra)`

Before, I was using this:

          `tbst=TextBoxStyle(opentype.GlyphAccumulatorFactory('Arial-BoldMT.ttf'),font_size=10)`

You are right  and probaly is something wrong in my code or in my OS dependencies.

**Comment by MatthiasValvekens** [comment]
Yeah, that one failing test could be due to pythonpath issues (it seems to be prioritising the installed version of pyhanko over what's in the tree for some reason). The skips are also expected if you don't pass the environment variables for imagemagick and pdftoppm.

> Nevertheless, I have solved it using SimpleFontEngineFactory instead of GlyphFontEngineFactory as follow:

If that works for you: great, but be aware that the font handling for `SimpleFontEngineFactory` is totally different. Nothing will be embedded into the file, and your PDF viewer will go look for a Type1 font named "Arial-BoldMT.ttf". Most likely it won't find any such font (even if the file is there, since TTF and PostScript Type1 are very different font technologies) and substitute a fallback font of its own.

If you're happy with that: great, but if that's not what you expect, then you might want to spend some more time figuring out why `uharfbuzz` doesn't do what we think it should do on your machine :).

**Comment by ilpadrinohack** [comment]
After exporting the enviroment variables for imagemagick and pdftoppm, these are the results:

       `[root@pc-131 pyhanko]# python -m pytest pyhanko_tests/test_stamp.py
         ========================================= test session starts 
         =========================================
         platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
         rootdir: /usr/local/lib/python3.10/site-packages/pyhanko
         collected 23 items                                                                                    

         pyhanko_tests/test_stamp.py ........FFFF...........                                             [100%]

         ============================================== FAILURES 
         ===============================================
         ______________________________________ test_four_qr_stamps[True] 
         ______________________________________

     fixed_size = True

    @with_layout_comparison
    @pytest.mark.parametrize('fixed_size', [True, False])
    def test_four_qr_stamps(fixed_size):
        # Share a font subset, the text is the same everywhere
        gaf = GlyphAccumulatorFactory(NOTO_SANS, font_size=10)
        w = empty_page()
        positions = ((10, 700), (10, 500), (10, 10), (260, 10))
        for qr_pos, (x, y) in zip(QRPosition, positions):
            style = QRStampStyle(
                stamp_text='Test stamp text\nAnother line of text',
                text_box_style=TextBoxStyle(font=gaf),
                qr_position=qr_pos, background=STAMP_ART_CONTENT,
                background_opacity=0.4
            )
            if fixed_size:
                if qr_pos.horizontal_flow:
                    box = layout.BoxConstraints(width=300, height=100)
                else:
                    box = layout.BoxConstraints(width=100, height=300)
            else:
                box = None
            ts = QRStamp(
                writer=w, style=style, box=box, url='https://example.com'
            )
            ts.apply(0, x=x, y=y)
        postfix = 'fixed' if fixed_size else 'natural'
         >       compare_output(w, f'{EXPECTED_OUTPUT_DIR}/four-stamps-{postfix}.pdf')

         pyhanko_tests/test_stamp.py:172: 
         _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

         writer = <pyhanko.pdf_utils.writer.PdfFileWriter object at 0x7f6479a08be0>
         expected_output_path = 'pyhanko_tests/data/pdf/layout-tests/four-stamps-fixed.pdf'

    def compare_output(writer: BasePdfFileWriter, expected_output_path):
        with tempfile.TemporaryDirectory() as working_dir:
            output_path = os.path.join(working_dir, 'output.pdf')
            with open(output_path, 'wb') as outf:
                writer.write(outf)
            expected_png = _render_pdf(
                expected_output_path, os.path.join(working_dir, 'expected')
            )
            actual_png = _render_pdf(
                output_path, os.path.join(working_dir, 'actual')
            )
            result = subprocess.run(
                # use the Absolute Error metric, since it's a single number
                # and hence very easy to process
                [
                    compare_path, '-metric', 'ae',
                    expected_png, actual_png, os.path.join(working_dir, 'diff.png')
                ],
                capture_output=True
            )
            if result.stderr != b'0':
                dest_dir = _ensure_path("failed_layout_tests", expected_output_path)
                shutil.copy(output_path, os.path.join(dest_dir, "output.pdf"))
                from_workdir = ('actual.png', 'diff.png', 'expected.png')
                for f in from_workdir:
                    shutil.copy(
                        src=os.path.join(working_dir, f),
                        dst=os.path.join(dest_dir, f),
                        follow_symlinks=False
                    )
                shutil.copy(os.path.join(working_dir, 'diff.png'), dest_dir)
                shutil.copy(os.path.join(working_dir, 'expected.png'), dest_dir)
         >               raise RuntimeError(
                    f"Output compare test failed --- absolute error: "
                    f"{result.stderr.decode('utf8')}; "
                    f"Output saved in {dest_dir}."
                )
         E               RuntimeError: Output compare test failed --- absolute error: 11328; Output saved in 
         failed_layout_tests/pyhanko_tests/data/pdf/layout-tests/four-stamps-fixed.pdf_results.

         pyhanko_tests/layout_test_utils.py:84: RuntimeError
         _____________________________________ test_four_qr_stamps[False] 
               ______________________________________
 
      fixed_size = False

    @with_layout_comparison
    @pytest.mark.parametrize('fixed_size', [True, False])
    def test_four_qr_stamps(fixed_size):
        # Share a font subset, the text is the same everywhere
        gaf = GlyphAccumulatorFactory(NOTO_SANS, font_size=10)
        w = empty_page()
        positions = ((10, 700), (10, 500), (10, 10), (260, 10))
        for qr_pos, (x, y) in zip(QRPosition, positions):
            style = QRStampStyle(
                stamp_text='Test stamp text\nAnother line of text',
                text_box_style=TextBoxStyle(font=gaf),
                qr_position=qr_pos, background=STAMP_ART_CONTENT,
                background_opacity=0.4
            )
            if fixed_size:
                if qr_pos.horizontal_flow:
                    box = layout.BoxConstraints(width=300, height=100)
                else:
                    box = layout.BoxConstraints(width=100, height=300)
            else:
                box = None
            ts = QRStamp(
                writer=w, style=style, box=box, url='https://example.com'
            )
            ts.apply(0, x=x, y=y)
        postfix = 'fixed' if fixed_size else 'natural'
         >       compare_output(w, f'{EXPECTED_OUTPUT_DIR}/four-stamps-{postfix}.pdf')

        pyhanko_tests/test_stamp.py:172: 
        _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

        writer = <pyhanko.pdf_utils.writer.PdfFileWriter object at 0x7f6479f40580>
     expected_output_path = 'pyhanko_tests/data/pdf/layout-tests/four-stamps-natural.pdf'

    def compare_output(writer: BasePdfFileWriter, expected_output_path):
        with tempfile.TemporaryDirectory() as working_dir:
            output_path = os.path.join(working_dir, 'output.pdf')
            with open(output_path, 'wb') as outf:
                writer.write(outf)
            expected_png = _render_pdf(
                expected_output_path, os.path.join(working_dir, 'expected')
            )
            actual_png = _render_pdf(
                output_path, os.path.join(working_dir, 'actual')
            )
            result = subprocess.run(
                # use the Absolute Error metric, since it's a single number
                # and hence very easy to process
                [
                    compare_path, '-metric', 'ae',
                    expected_png, actual_png, os.path.join(working_dir, 'diff.png')
                ],
                capture_output=True
            )
            if result.stderr != b'0':
                dest_dir = _ensure_path("failed_layout_tests", expected_output_path)
                shutil.copy(output_path, os.path.join(dest_dir, "output.pdf"))
                from_workdir = ('actual.png', 'diff.png', 'expected.png')
                for f in from_workdir:
                    shutil.copy(
                        src=os.path.join(working_dir, f),
                        dst=os.path.join(dest_dir, f),
                        follow_symlinks=False
                    )
                shutil.copy(os.path.join(working_dir, 'diff.png'), dest_dir)
                shutil.copy(os.path.join(working_dir, 'expected.png'), dest_dir)
       >               raise RuntimeError(
                    f"Output compare test failed --- absolute error: "
                    f"{result.stderr.decode('utf8')}; "
                    f"Output saved in {dest_dir}."
                )
      E               RuntimeError: Output compare test failed --- absolute error: 8151; Output saved in 
           failed_layout_tests/pyhanko_tests/data/pdf/layout-tests/four-stamps-natural.pdf_results.

           pyhanko_tests/layout_test_utils.py:84: RuntimeError
      _________________________________________ test_fancy_qr_stamp 
        _________________________________________

    def test_fancy_qr_stamp():
        w = empty_page()
   >       style = QRStampStyle(
            stamp_text='Test stamp text\nAnother line of text',
            qr_inner_content=STAMP_ART_CONTENT,
        )
       E       TypeError: QRStampStyle.__init__() got an unexpected keyword argument 'qr_inner_content'

       pyhanko_tests/test_stamp.py:177: TypeError
       __________________________________ test_japanese_vertical_text_stamp __________________________________

    @with_layout_comparison
    def test_japanese_vertical_text_stamp():
        gaf = GlyphAccumulatorFactory(
            NOTO_SERIF_JP, font_size=10, writing_direction='ttb'
        )
        w = empty_page()
        style = QRStampStyle(
            stamp_text=(
                'テスト\n縦書きテスト\n改行してみましょう（括弧）\nPDF\n'
                'ちょっと長めの文を書いてみた。'
            ),
            text_box_style=TextBoxStyle(font=gaf, vertical_text=True),
            qr_position=QRPosition.ABOVE_TEXT,
            background=STAMP_ART_CONTENT,
            background_opacity=0.4
        )
        box = layout.BoxConstraints(width=100, height=300)
        ts = QRStamp(writer=w, style=style, box=box, url='https://example.com')
        ts.apply(0, x=10, y=415)
        ts = QRStamp(writer=w, style=style, box=None, url='https://example.com')
        ts.apply(0, x=400, y=415)
       >       compare_output(w, f'{EXPECTED_OUTPUT_DIR}/ja-vert-stamps.pdf')

       pyhanko_tests/test_stamp.py:210: 
       _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

      writer = <pyhanko.pdf_utils.writer.PdfFileWriter object at 0x7f6479a3afe0>
      expected_output_path = 'pyhanko_tests/data/pdf/layout-tests/ja-vert-stamps.pdf'

    def compare_output(writer: BasePdfFileWriter, expected_output_path):
        with tempfile.TemporaryDirectory() as working_dir:
            output_path = os.path.join(working_dir, 'output.pdf')
            with open(output_path, 'wb') as outf:
                writer.write(outf)
            expected_png = _render_pdf(
                expected_output_path, os.path.join(working_dir, 'expected')
            )
            actual_png = _render_pdf(
                output_path, os.path.join(working_dir, 'actual')
            )
            result = subprocess.run(
                # use the Absolute Error metric, since it's a single number
                # and hence very easy to process
                [
                    compare_path, '-metric', 'ae',
                    expected_png, actual_png, os.path.join(working_dir, 'diff.png')
                ],
                capture_output=True
            )
            if result.stderr != b'0':
                dest_dir = _ensure_path("failed_layout_tests", expected_output_path)
                shutil.copy(output_path, os.path.join(dest_dir, "output.pdf"))
                from_workdir = ('actual.png', 'diff.png', 'expected.png')
                for f in from_workdir:
                    shutil.copy(
                        src=os.path.join(working_dir, f),
                        dst=os.path.join(dest_dir, f),
                        follow_symlinks=False
                    )
                shutil.copy(os.path.join(working_dir, 'diff.png'), dest_dir)
                shutil.copy(os.path.join(working_dir, 'expected.png'), dest_dir)
       >               raise RuntimeError(
                    f"Output compare test failed --- absolute error: "
                    f"{result.stderr.decode('utf8')}; "
                    f"Output saved in {dest_dir}."
                )
       E               RuntimeError: Output compare test failed --- absolute error: 5183; Output saved in 
       failed_layout_tests/pyhanko_tests/data/pdf/layout-tests/ja-vert-stamps.pdf_results.

       pyhanko_tests/layout_test_utils.py:84: RuntimeError
        ======================================= short test summary info 
        =======================================
        FAILED pyhanko_tests/test_stamp.py::test_four_qr_stamps[True] - RuntimeError: Output compare test fa...
        FAILED pyhanko_tests/test_stamp.py::test_four_qr_stamps[False] - RuntimeError: Output compare test f...
        FAILED pyhanko_tests/test_stamp.py::test_fancy_qr_stamp - TypeError: QRStampStyle.__init__() got an ...
        FAILED pyhanko_tests/test_stamp.py::test_japanese_vertical_text_stamp - RuntimeError: Output compare...
        ==================================== 4 failed, 19 passed in 9.04s 
        =====================================
`
Also have checked all in the requirements.txt  and all seems to be OK.  I will continue insisting

**Comment by MatthiasValvekens** [comment]
Sorry, apparently I forgot to reply to this one again.

So, all of the failing tests you see can be explained as the result of running the test suite on current `master` against a release version of pyHanko (I changed some of the QR handling code recently). In particular, the font-related ones seem to be all green. That would indicate that the issue is somewhere in your code.

I'm having trouble reading exactly what you tried due to the many commented-out lines, but try initialising your text stamp style like this:

```python
    fnt = GlyphAccumulatorFactory(NOTO_SANS, font_size=10)

    style = TextStampStyle(
        stamp_text="Your text goes here",
        text_box_style=TextBoxStyle(font=fnt),
    )
```

Don't forget the keyword names! `TextBoxStyle(font=fnt)` is _not_ the same thing as `TextBoxStyle(fnt)`, for example.

**Comment by ilpadrinohack** [comment]
Hi Matthias, sorry for the delay, but at least I have found out what was happening.

It was when attempting to get a string from the data of the certificate to use it in `stamp_text.` If I insert  a double `\n` for get a breakline in the final string, I get the error:
    `TypeError: 'NoneType' object is not iterable`

But if I build it without `\n`, it works.

This was my original code with the error:
     `datos_firma=f'Firma digital por:\n\n{nombre}.\n\nDNI/CIF:{cif}\n'
       style=TextStampStyle(text_box_style=tbst,stamp_text=datos_firma,border_width=0)`

and building it as:

      `l = ['Firma Digital por:', nom, 'DNI/CIF:'+cif]
       s_n = '\n'.join(l)
       style=TextStampStyle(text_box_style=tbst,stamp_text=s_n,border_width=0)`

works perfectly. Finally it was not related to font management. I don't know if the way of concatenating string have changed in the latest python version 

Thanks for all your help
Best regards

**Comment by MatthiasValvekens** [comment]
> It was when attempting to get a string from the data of the certificate to use it in stamp_text. If I insert a double \n for get a breakline in the final string, I get the error:
> TypeError: 'NoneType' object is not iterable
> But if I build it without \n, it works.

Thanks, this was really useful info! I can now reproduce the error you're seeing. It turns out that `uharfbuzz` returns `glyph_positions=None` in the shaping results buffer when you pass it an empty string (which would've been the case here, since we first break up the string into lines before involving the shaper). I'll commit a fix very soon.

Thank you!
