### ISSUE TITLE
Get token pin from ENV variable or as cli argument for pkcs11

### ISSUE THREAD

**Issue by asaid-0** [MatthiasValvekens/pyHanko#142]
**Is your feature request related to a problem? Please describe.**
I need to pass the token pin as an ENV variable or option to the CLI command

```
PKCS11_TOKEN_PIN=12345678 pyhanko --verbose sign addsig --field Sig1 pkcs11 \
    --cert-label testcrt --key-label testpriv --token-label FixedMisr sig1-test2.pdf test22-signed.pdf
```

**Comment by MatthiasValvekens** [comment]
Sounds reasonable enough. I'll look into it and get back to you.

**Comment by MatthiasValvekens** [comment]
Done (see linked commit). In the next release, you'll be able to use the `PYHANKO_PKCS11_PIN` env var for this purpose.
