### ISSUE TITLE
Error when trying to sign using a p12 certificate file

### ISSUE THREAD

**Issue by ilpadrinohack** [MatthiasValvekens/pyHanko#17]
I have upgraded my system and python has upgraded from 3.8 to 3.9. On version 3.8 everything worked fine, but now I have got this error which I do not know how to solve. Error occurs when I get a p12 file  certificate to sign, when is verifying the certificate. This is the error:
    `File "/root/Descargas/programacion/firma_digital/pades_sign/firma_final.py", line 307, in certificadodig
    out = signers.PdfSigner(signature_meta=signers.PdfSignatureMetadata(
  File "/usr/local/lib/python3.9/site-packages/pyhanko/sign/signers.py", line 2198, in sign_pdf
    signer_cert_validation_path = validator.validate_usage(
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/__init__.py", line 211, in validate_usage
    self._validate_path()
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/__init__.py", line 139, in _validate_path
    validate_path(self._context, candidate_path, self._params)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py", line 70, in validate_path
    return _validate_path(validation_context, path, parameters=parameters)
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py", line 661, in _validate_path
    qualified_policies = _finish_policy_processing(
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py", line 741, in _finish_policy_processing
    qualified_policies = frozenset(_enum_policies())
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py", line 732, in _enum_policies
    user_domain_policy_id=next(
  File "/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py", line 735, in <genexpr>
    if ancestor.parent.valid_policy == 'any_policy'
  AttributeError: 'PolicyTreeRoot' object has no attribute 'valid_policy'`

 My pyhanko version is 0.6.1 and the pyhanko-certvalidator  is 0.15.1 (I have als tested 0.15.2 with same result)

The code is :

     ` def certificadodigper(x1,y1,x2,y2,fname):
        try:  
            root.filename =  filedialog.askopenfilename(initialdir = ".",title = "Seleccione archivo",filetypes = (("p12 files","*.p12"),("all files","*.*")))
            finame=root.filename
            w = IncrementalPdfFileWriter(BytesIO(MINIMAL))
            pin=simpledialog.askstring(title = 'Introduzca PIN', prompt='PIN secreto', show ='*')
            FROM_CA_PKCS12 = signers.SimpleSigner.load_pkcs12(
            finame, passphrase=bytes(pin,'utf-8'))

            p12 = crypto.load_pkcs12(open(finame, 'rb').read(), bytes(pin,'utf-8'))

            acert=p12.get_certificate()     # (signed) certificate object
            bkey=p12.get_privatekey()      # private key.
            cinter=p12.get_ca_certificates() # ca chain.   

            certs =crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, acert)
            certt2=crypto.load_certificate(FILETYPE_PEM,certs)
            subject=certt2.get_subject()
            print(subject)

            nombre = dict(subject.get_components())[b'CN'].decode()
            cif = dict(subject.get_components())[b'serialNumber'].decode()
            #empresa=dict(subject.get_components())[b'O'].decode()
            privkey=crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, bkey)
            datos_firma=f'Firma digital por:\n\n{nombre}.\n\nDNI/CIF:{cif}\n'
            sv = fields.SigSeedValueSpec(
                    reasons=[],            
                    flags=3,
                    )

            
            letra=SimpleFontEngine('Arial-BoldMT',0.4)  
            sp = fields.SigFieldSpec('Sigg1', seed_value_dict=sv, on_page=pagina_firma-1, box=(x1, y1, x2, y2),)
            tbst=TextBoxStyle( letra,)
                #image = PdfImage(image=settings.STAMP_IMAGE)
            vc = ValidationContext(trust_roots=[FROM_CA_PKCS12.signing_cert])    
            if (firma.ci==False):
                style=TextStampStyle(text_box_style=tbst,stamp_text=datos_firma,border_width=0)
            else:    
                style=TextStampStyle(text_box_style=tbst,stamp_text=datos_firma, background=PdfImage(cargaimagen.imname),border_width=0,background_opacity=0.4)
            fname = fname.replace('.pdf', '-f.pdf')
            with open(fname, 'wb') as outf:

                out = signers.PdfSigner(signature_meta=signers.PdfSignatureMetadata(
                                                    field_name='Sigg1',
                                                    reason='Firma',
                                                    location='', 
                                                    use_pades_lta=True,
                                                    subfilter=fields.SigSeedSubFilter.PADES,
                                                    embed_validation_info=True,
                                                    validation_context=vc
                                                    ),
                                    signer=FROM_CA_PKCS12,
                                    timestamper=None,
                                    stamp_style=style,
                                    new_field_spec=sp
                                    ).sign_pdf(w, output=outf)

            print(nombre,cif)  

        except TypeError:
                        salidaerror=messagebox.askokcancel("ERROR!!!!","Ha habido un error en la firma\n Aségurese de que el fichero                es el correcto y la clave es la correcta")
                        if salidaerror==True:
                            parent.destroy()
        else:
                        salida=messagebox.askokcancel("Fichero firmado","Se ha realizado la firma correctamente\n Se ha guardado el archivo con el mismo nombre + la 'f'")
                        if salida==True:
                            
                            parent.destroy()       `

I have changed my code according to changes in the new release:

      `from certvalidator import ValidationContext` 

     to

     `from pyhanko_certvalidator import ValidationContext` 

Thanks in advance

**Comment by MatthiasValvekens** [comment]
Thanks for moving your report to a new issue!

I see. I was going to ask whether you updated the certvalidator import, but it seems that you did. Anyway, it appears that this could be a bug in the certification policy reporting code in `pyhanko_certvalidator`. Can you share the relevant certificates (without the corresponding private keys) so that I can properly diagnose the issue and generate test certs for a regression test?

If you're not comfortable posting the certificates here, you can send them to me by email: drop me a message at pyhanko.samples [at mark goes here] mvalvekens.be.

**Comment by ilpadrinohack** [comment]
Thanks for the quick answer, and solution!!!. Nevertheless , I haven sent you the certificate without passphrase (pyhanko.samples@mvalvekens.be).

Thanks again
