### ISSUE TITLE
DivisionByZero error when rendering a text box with empty string

### ISSUE THREAD

**Issue by peteris-zealid** [MatthiasValvekens/pyHanko#170]
**Describe the bug**
DivisionByZero error when rendering a text box with empty string.

I did not manage to reproduce the issue through the cli, but I was doing something wrong because I did not manage to get a visual text box at all.

**Additional context**
in `TextStamp::_inner_layout_natural_size` the variable `inn_box.width` can have value 0 that will create math problems down the line. This will happen if the text is an empty string.

**Comment by MatthiasValvekens** [comment]
Good catch! I found the error and added a safeguard (see linked commit); I'll merge that one tonight. Triggering this requires setting a bunch of default margins to zero, and is potentially tricky to do through the CLI, but it's a bug nonetheless.

Thanks!
