### ISSUE TITLE
Application name was not added in advanced signature properties

### ISSUE THREAD

**Issue by TechStackGit** [MatthiasValvekens/pyHanko#192]
![image](https://user-images.githubusercontent.com/119850325/206398206-f3b8276b-9e2b-4aeb-8b10-01f530931692.png)
Is there a way to configure the application name in the signature properties instead of Not Available
Reference: [endesive](https://github.com/m32/endesive/issues/139)

**Comment by MatthiasValvekens** [comment]
Hi, as I explained over in #195, I never bothered to implement this feature due to lack of interest, but @ganesharavindh kindly provided a PR which will take care of this. I'll put a link to the updated API documentation once it's merged :).

**Comment by TechStackGit** [comment]
@MatthiasValvekens That's great, I will install this from source and kindly release this module as a stable version(once you do all testing) so that it will be available in PyPI.
