### ISSUE TITLE
'SigFieldSpec' Object is not iterable

### ISSUE THREAD

**Issue by ilpadrinohack** [MatthiasValvekens/pyHanko#2]
According to documentation, I am trying to add a signature field to a PDF document, so:

This is my code:
      
      `from  pyhanko.sign.fields import append_signature_fields,SigFieldSpec
       from pyhanko.pdf_utils.incremental_writer import IncrementalPdfFileWriter
       with open('output-signed.pdf', 'rb+') as doc:
                    w = IncrementalPdfFileWriter(doc)      
                    append_signature_fields(w, SigFieldSpec(sig_field_name='Sig'))
                    w.write_in_place()`

I had to change"append_signature_field" for "append_signature_fields", but no matter the parameters I add to SigFieldSpec, that I have always the same result which is  'SigFieldSpec' object is not iterable.

But my CLI version works perfecly

Any help will be grateful
Thanks in advance

**Comment by MatthiasValvekens** [comment]
Hi, thanks for posting!

That bit of API changed in commit a3ffbdb7, and that's what the documentation reflects. The point is that `add_signature_field` used to be called `add_signature_fields` (note the plural), and take a list of `SigFieldSpec` objects as input. I decided that that was counterintuitive, so I tweaked the API a little.

I think you might be using an older version of the codebase.
Can you try pulling master and/or with the 0.1.0 alpha release, and see if your issue persists?


PyHanko's signing API isn't fully stable yet, and probably won't be until 1.0.0 is released. Sorry about that! Anyway, even before we reach that point, all future minor releases will come with a changelog, which will definitely document any high-level API breakage.

**Comment by ilpadrinohack** [comment]
Hi Matthias:

Thanks for your reply. I have upgraded to the latest release and now works
like a charm. Now I am trying to sign with a PKCS11 device (Spanish eID
card), which seems to be a little bit messy.
Nevertheless, congratulations for your code and hope you will be successful
in future releases. Once again, thank you very much.

Best regards
Fernando

**Comment by MatthiasValvekens** [comment]
Thanks a lot!

My experience with PKCS#11 is pretty limited, so I only fully implemented an adapter for the Belgian eID (that's all I had to test with).

Provided that the Spanish cards also use RSA-based keys, it shouldn't be too hard to adapt the BeID implementation to your needs.
If you manage to figure out how to get the Spanish one to work, I'd hugely appreciate it if you could report your findings (either by opening another issue and/or pull request). The more input I get, the easier it'll be to get support for general PKCS#11 in the future. :)

**Comment by ilpadrinohack** [comment]
Hi Mathias again. Sorry for the disturbance. I have upgraded my system and
python has upgraded from 3.8 to 3.9. On version 3.8 everything worked fine,
but now I have got this error which I do not know how to solve. Error
occurs when I get a p12 file  certificate to sign, when is verifying the
certificate. This is the error:

File
"/root/Descargas/programacion/firma_digital/pades_sign/firma_final.py",
line 307, in certificadodig
    out = signers.PdfSigner(signature_meta=signers.PdfSignatureMetadata(
  File "/usr/local/lib/python3.9/site-packages/pyhanko/sign/signers.py",
line 2198, in sign_pdf
    signer_cert_validation_path = validator.validate_usage(
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/__init__.py",
line 211, in validate_usage
    self._validate_path()
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/__init__.py",
line 139, in _validate_path
    validate_path(self._context, candidate_path, self._params)
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py",
line 70, in validate_path
    return _validate_path(validation_context, path, parameters=parameters)
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py",
line 661, in _validate_path
    qualified_policies = _finish_policy_processing(
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py",
line 741, in _finish_policy_processing
    qualified_policies = frozenset(_enum_policies())
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py",
line 732, in _enum_policies
    user_domain_policy_id=next(
  File
"/usr/local/lib/python3.9/site-packages/pyhanko_certvalidator/validate.py",
line 735, in <genexpr>
    if ancestor.parent.valid_policy == 'any_policy'
*AttributeError: 'PolicyTreeRoot' object has no attribute 'valid_policy'*


Is it something related to the new python version??

Thanks in advance
Fernando

**Comment by MatthiasValvekens** [comment]
Can you open a new issue for this, and post your package versions for `pyhanko-certvalidator` and `pyHanko` there? The former has seen some changes recently. See the [release notes](https://pyhanko.readthedocs.io/en/latest/changelog.html#id2) for pyHanko 0.6.0 for more information on how this affects existing pyHanko code. :)

I run CI tests against Python 3.7, 3.8 and 3.9 for both of these packages, so the change in Python versions is probably not the root cause here.
