### ISSUE TITLE
setup.py bug

### ISSUE THREAD

**Issue by peteris-zealid** [MatthiasValvekens/pyHanko#20]
Maybe I do not understand how setup.py works, but I think this diff should be applied.

```
diff --git a/setup.py b/setup.py
index 14f1ea5..722d2e5 100644
--- a/setup.py
+++ b/setup.py
@@ -23,7 +23,7 @@ setup(
     packages=[
         'pyhanko',
         'pyhanko.pdf_utils', 'pyhanko.pdf_utils.font',
-        'pyhanko.sign', 'pyhanko.sign.ades',
+        'pyhanko.sign', 'pyhanko.sign.ades', 'pyhanko.sign.signers',
     ],
     url='https://github.com/MatthiasValvekens/pyHanko',
     license='MIT',
```

The problem is that I failed to install pyhanko master branch using pipenv.

**Comment by peteris-zealid** [comment]
Thank you very much for the high quality software - I appreciate it.

**Comment by MatthiasValvekens** [comment]
That package was added very recently, and isn't part of any tagged release yet. But you're absolutely right that it needs to be added. Will take care of that tonight. :)
