### ISSUE TITLE
Digital Signature is visible as blue box in Adobe Reader

### ISSUE THREAD

**Issue by ratnamkamlesh** [MatthiasValvekens/pyHanko#243]
**Describe the bug:-**
Digitally sign pdf file using pyHanko and when open this file to adobe reader showed a blue box of digital signature and I can not validate the digital signature.

**To Reproduce**
Sign any PDF file using pyHanko, and open it in adobe reader.

**Screenshots**.
![image](https://user-images.githubusercontent.com/55582058/226604867-7c3ca173-0eda-4267-a2f6-8d7802688cfc.png)

**Environment (please complete the following information):**
OS: Ubuntu 20.04.6 LT
Version: Latest pyHanko with Python 3.7

**Additional context**
  N/A
Amazing work of pyHanko, which is incredibly useful.

**Comment by MatthiasValvekens** [comment]
>  Sign any PDF file using pyHanko, and open it in adobe reader.

Well, you're going to have to give us more steps to reproduce than that, because it works for me ;). Share your code, or the exact CLI invocation you tried.

This looks like you're generating PDFs with an empty signature field instead of a filled one at first sight.
