### ISSUE TITLE
Needs a requirements.txt file

### ISSUE THREAD

**Issue by IJOL** [MatthiasValvekens/pyHanko#258]
To have this repository handled automatically by devtools it needs a current requirements.txt file

**Comment by MatthiasValvekens** [comment]
Hi,


I recently removed the requirements.txt file in favour of putting everything in pyproject.toml. A PEP 621-compliant toolchain should be able to extract the information it needs from there.

**Comment by IJOL** [comment]
Oh, good to know i dont have a PEP-621 compliant toolchain, but until all
my toolchain comply ( pycharm latest ) , would be awesome if you re add the
file to git main, i can commit to maintain that file until my tool chain
evolves for the good.. deal?


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by MatthiasValvekens** [comment]
I do my development in Pycharm as well, FWIW :)

You can always install the dependencies you need into your venv with `pip -e .[testing]`.
