### ISSUE TITLE
cli --no-strict-syntax missing

### ISSUE THREAD

**Issue by jtplaarj** [MatthiasValvekens/pyHanko#262]
**Describe the bug**

Option `--no-strict-syntax` does not exist.

**To Reproduce**

```bash
pyhanko  sign addfields --no-strict-syntax --field 1/0,0,100,200/test test_in.pdf test_out.pdf
Usage: pyhanko sign addfields [OPTIONS] INFILE OUTFILE
Try 'pyhanko sign addfields --help' for help.

Error: No such option: --no-strict-syntax
```

**Expected behavior**

According to the documentation option `--no-strict-syntax` should exist. In fact, the command is recommended by the cli due to a problem in the PDF:

```bash
2023-05-23 12:09:55,676 - cli - ERROR - Failed to read PDF file in strict mode; rerun with --no-strict-syntax to try again.
Error message: Object with id 273 has an orphaned generation: generation 1 was not preceded by a free instruction for generation 0.
Error: Failed to read PDF file in strict mode; rerun with --no-strict-syntax to try again.
Error message: Object with id 273 has an orphaned generation: generation 1 was not preceded by a free instruction for generation 0.
```

**Environment (please complete the following information):**
 - pyhanko version 0.18.1 installed using pip
 - python version: 3.11.3
 - OS: iOS 22.4.0 and Debian 5.10.162-1

**Comment by MatthiasValvekens** [comment]
Looks like it's not registered on the `addfields` subcommand. Will take a look. Thanks!

**Comment by MatthiasValvekens** [comment]
I have a fix pending that makes all non-cryptographic CLI commands implicitly use nonstrict mode (see linked PR). `addfields` is one of those, so your case should be covered :).
