### ISSUE TITLE
enhance document to provide concret example for specifying the page and coordinates of the signature field

### ISSUE THREAD

**Issue by LeiYangGH** [MatthiasValvekens/pyHanko#278]
In the CLI documents, https://pyhanko.readthedocs.io/en/latest/cli-guide/signing.html#creating-signature-fields
There's such command line example
`--field  PAGE/X1,Y1,X2,Y2/NAME`
but it is difficult to understand what real numbers should be even read the following paragraph.
for example, i know `PAGE` should be replaced with page number, `X1,Y1,X2,Y2` stands for some coordinates. but what does the `NAME` mean and what should it be replaced with?
it would be great if provide concret example, thanks!

**Comment by MatthiasValvekens** [comment]
Fair enough, that could be made more clear.

- `PAGE` is the page number
- `X1,Y1,X2,Y2` are the coordinates of two opposing corners of the signature bbox (traditionally, lower left and upper right)
- `NAME` is the name of the signature field to create.

I'll add this to the docs.

**Comment by LeiYangGH** [comment]
thanks for the quick action!
