### ISSUE TITLE
Link to the documentation in description

### ISSUE THREAD

**Issue by hyzyla** [MatthiasValvekens/pyHanko#306]
I usually try to find the documentation somewhere at the top of the README.md file or in the project description. But you have a link at the bottom of the file that I didn't find the first time. Could you add documentation to the project description?

![CleanShot 2023-08-23 at 13 29 09@2x](https://github.com/MatthiasValvekens/pyHanko/assets/7952949/e422a32f-83b9-4167-9b98-2df7673ae488)

P.S. Btw, thank you for the library!

**Comment by MatthiasValvekens** [comment]
The project description is a single-line field which doesn't really jive well with external links, but you have a point. I moved the documentation section of the readme closer to the top, and reworded it to be more clear.
