### ISSUE TITLE
Doubt: support TSA using socket connection on port 318?

### ISSUE THREAD

**Issue by silvaartur** [MatthiasValvekens/pyHanko#36]
Doubt: support TSA using socket connection on port 318?

**Comment by MatthiasValvekens** [comment]
Hi Artur,

I’m not sure I fully understand your question. PyHanko supports fetching
timestamp
tokens using the RFC 3161 protocol over HTTP. Typically, that means that
traffic goes through port 80 (RFC 3161 traffic rarely goes over HTTPS).
However, nothing stops you from putting any port you want into the URL.

Example: “http://myfavouritetsa.org:316/path/to/endpoint”.

If the protocol you want to use is not the one in RFC 3161, you can still
implement your own TimeStamper subclass, in principle (fair warning: there
will be breaking API changes in the next release).

**Comment by MatthiasValvekens** [comment]
Hi Artur,


Sorry, I was a little slow on the uptake. You’re referring to the non-HTTP
version of the time stamping protocol in RFC 3161, right? In that case,
you’ll have to subclass TimeStamper for now. You’ll still be able to
recycle most of the code, though.
