### ISSUE TITLE
Exception when signing a PDF with filled forms

### ISSUE THREAD

**Issue by fredericoschardong** [MatthiasValvekens/pyHanko#39]
Hey Matthias,

I have been playing arround the subject of our last discussion: signing filled forms, but hit a roadblock. Here it is:

**Describe the bug**
I get `pyhanko.pdf_utils.misc.PdfReadError` when signing a pdf with any filled form I could find. Perhaps the forms are not A-grade and are the root cause of the issue, or the programs I am using to fill them (okular and evince). I can sign any pdf with forms just fine if and only if they are empty.

**To Reproduce**
1. Download [example.zip](https://github.com/MatthiasValvekens/pyHanko/files/7297587/example.zip) 
2. Fill the form.pdf and save the resulting pdf under the same name
3. Run `python3 sign.py` to sign the filled form and get an error like `pyhanko.pdf_utils.misc.PdfReadError: Generation 0 of object 3 was never freed, but reused later.`

**Expected behavior**
No errors and a signed pdf.

**Environment (please complete the following information):**
 - OS: ubuntu
 - Version: 21.04

**Comment by MatthiasValvekens** [comment]
That's a valid question. The logic for DocMDP policies on an approval signature (i.e. a signature that's not a certification signature) is a bit wonky, and in case of `NO_CHANGES`, I should probably tighten up this piece of fallback logic that's used when there's no field lock dictionary on the field: https://github.com/MatthiasValvekens/pyHanko/blob/6eef056fb5ac32f87fedc9ae8dc1181c3a45adac/pyhanko/sign/signers/pdf_signer.py#L1288-L1295. I guess it makes sense to call that a bug.

In the meantime, you can try creating a signature field with a field lock dictionary that locks everything, and then sign that. Here's the documentation on how to do field locking in pyHanko: https://pyhanko.readthedocs.io/en/latest/lib-guide/sig-fields.html#document-modification-policy-settings. You can combine that with a DocMDP policy setting, which is very common, but it's a PDF 2.0 thing, and it's pretty poorly specified in general (it's a common source of complaints in the industry).

Also, in case you're not already doing that: in multi-signer workflows, it's good practice to create all visible signature fields before filling them. The rationale behind that is that the initial signer should have the right to know where all the other signatures will go, so they can make sure that the visual appearances of later signatures won't change the meaning of any document content. Not all validators enforce that principle, though. PyHanko's only does it by default if a certification signature is present.

So the ideal workflow is more or less this:

 - Set up all form fields, with field lock dictionaries for the signature fields if necessary. You can put a DocMDP `NO_CHANGES` trigger on the field that will be signed last (subject to the caveats from above)
 - Optionally put in a visible or invisible certification signature with DocMDP set to "form filling" (if that makes sense in your context)
 - Do form filling operations
 - Put in the "regular" signatures

I can't do any real testing right now, but modulo some details I think this should work. :)
