### ISSUE TITLE
tests fail after 2030

### ISSUE THREAD

**Issue by bmwiedemann** [MatthiasValvekens/pyHanko#472]
**Describe the bug**
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds) (sponsored by the NLnet NGI0 fund), I found that
our `python-pyHanko` 0.25.1 package fails to build after 2030-01-01

**To Reproduce**
In Debian or openSUSE, you could do
osc checkout openSUSE:Factory python-pyHanko && cd $_
osc build --vm-type=kvm --noservice --clean --build-opt=--vm-custom-opt="-rtc base=2030-01-02T00:00:00" standard

It can probably also be triggered by changing the system clock 6 years forward. Or use libfaketime.

**Expected behavior**
Tests should keep working in the forseeable future (at least 16y).

**Screenshots**
```
 2030-01-02 00:03:14 WARNING The path could not be validated because the end-entity certificate expired 2030-01-01 00:00:00Z
 2030-01-02 00:03:14 WARNING Error in seed value validation.
 Traceback (most recent call last):
   File "/home/abuild/rpmbuild/BUILD/pyHanko-0.25.1/pyhanko/sign/validation/pdf_embedded.py", line 791, in report_seed_value_validation
     _validate_sv_constraints(
   File "/home/abuild/rpmbuild/BUILD/pyHanko-0.25.1/pyhanko/sign/validation/pdf_embedded.py", line 615, in _validate_sv_constraints
     raise SigSeedValueValidationError(
 pyhanko.sign.validation.errors.SigSeedValueValidationError: The seed value dictionary requires a trusted timestamp, but none was found, or the timestamp did not validate.
 FAILED                                                                   [ 60%]

```

**Environment (please complete the following information):**
 - OS: openSUSE-Tumbleweed 
 - Version 20240924

**Additional context**

python-pyhanko-certvalidator also has test future failures.

Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our package build.
See https://reproducible-builds.org/ for why this matters.

**Comment by MatthiasValvekens** [comment]
Hmm, that shouldn't happen indeed. I thought most tests in pyHanko's test suite already froze the clock, but there could indeed be some that don't. I'll check when I have time.

`pyhanko-certvalidator` is a little more tricky, because that codebase still has a couple integration tests that rely on the behaviour of actual repository servers operated by real CAs (shudder). Getting rid of those while retaining comparable coverage will require a little more development work.

**Comment by MatthiasValvekens** [comment]
I pushed some changes that should hopefully rectify this. I didn't test in a full VM with a manipulated clock, but `faketime '2030-01-02 00:00:00' pytest` now passes on my end. Do you still encounter issues on the master branch?

**Comment by bmwiedemann** [comment]
I tested our 0.25.1 package with commit 5bbc2ea4431cb7d7a10c4749c3214b689d8d82aa added. It passes all tests now with a date of 2040-11-22.

**Comment by MatthiasValvekens** [comment]
Alright, great! I'll leave this open until I get around to fixing the corresponding issues in pyhanko-certvalidator.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by MatthiasValvekens** [comment]
Issue in `pyhanko-certvalidator` sorta taken care of. The tests that should be run against a frozen clock were fixed. The "live" ones that can't reasonably work without a frozen clock were excluded from the default `pytest` scope and relegated to a separate integration test directory.

Does that work for you?

**Comment by bmwiedemann** [comment]
I tried pyhanko-certvalidator-0.26.4 and found that it still has 253 tests fail in 2040:
https://rb.zq1.de/other/python-pyhanko-certvalidator/build-log.txt

You should be able to test that on Debian and openSUSE with

```bash
osc checkout home:bmwiedemann:branches:devel:languages:python/python-pyhanko-certvalidator && cd $_
osc build --vm-type=kvm --noservice --clean --build-opt=--vm-custom-opt="-rtc base=2031-11-02T00:00:00" openSUSE_Tumbleweed
```

**Comment by MatthiasValvekens** [comment]
Ok, thanks! Will take another look later then... Strange.

**Comment by bmwiedemann** [comment]
I confirmed that https://github.com/MatthiasValvekens/certvalidator/commit/5dd5ff95b7b104667eb4f39367eb4f4c00fcedd5 makes it pass.

**Comment by MatthiasValvekens** [comment]
Fixes in `pyhanko` and `pyhanko-certvalidator` are now included in the latest release(s), so I'm going to close this. Thanks for flagging this issue!
