### ISSUE TITLE
The example in custom Signer using KMS section is wrong

### ISSUE THREAD

**Issue by minhhieu76qng** [MatthiasValvekens/pyHanko#486]
**Describe the bug**
I copied the example to run and there're several errors eg: initialize value in __init__ function.
But I fixed myself. When I run this code and open the file in Acrobat Reader, the signature is created but Acrobat said that `Signature is invalid` and `Signed by Unknown`

**To Reproduce**
https://pyhanko.readthedocs.io/en/latest/lib-guide/adv-examples.html

**Expected behavior**
The pdf file with valid Digital signature.

**Screenshots**
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/04994db5-1e53-4902-89ae-cf7056aa7609">

**Environment (please complete the following information):**
 - OS: [MacOS]
 - Version [pyhanko@0.25.1]

**Comment by minhhieu76qng** [comment]
```
class AsyncKMSSigner(Signer):
    def __init__(
        self,
        session: aioboto3.session,
        key_id: str,
        signing_cert: x509.Certificate,
        signature_mechanism: algos.SignedDigestAlgorithm,
        # this can be derived from the above, obviously
        signature_mechanism_aws_id: str,
        other_certs=(),
    ):
        self.session = session
        self.key_id = key_id
        self.signature_mechanism_aws_id = signature_mechanism_aws_id
        cr = SimpleCertificateStore()
        cr.register_multiple(other_certs)
        super().__init__(
            signing_cert=signing_cert,
            signature_mechanism=signature_mechanism,
            cert_registry=cr,
        )
```
This is how I changed the __init__ function. And the bellow is input of AsyncKMSSigner.
```
# Set up our signer
    signer = AsyncKMSSigner(
        session=session,
        key_id=kms_key_id,
        signing_cert=cert,
        other_certs=chain,
        # change the signature mechanism according to your key type
        # I'm using an ECDSA key over the NIST-P384 (secp384r1) curve here.
        signature_mechanism=algos.SignedDigestAlgorithm({"algorithm": "sha256_rsa"}),
        signature_mechanism_aws_id="RSASSA_PKCS1_V1_5_SHA_256",
    )
```

**Comment by MatthiasValvekens** [comment]
A few remarks:

- please post the actual output file, a screenshot doesn't really say much. It would also help if you could post the certificate file you used, the public half of your KMS key, and the exact code you ran (with secrets removed, obviously)
- You're probably right about the init function implementation being out of date, that should be fixed.
- The fact that you had to change the algorithm parameters is expected and explained by the comment right above the lines you changed: the example was written for a secp384r1 key, so if you use RSA, of course those lines need changing.


With the information available to me (which is not sufficient to make a full diagnosis) I suspect that the signer's cert doesn't match the KMS key.

**Comment by minhhieu76qng** [comment]
You are right. Our devops team provides the wrong KMS key with the signer's cert.
Thanks for your help and awesome project.
