### ISSUE TITLE
Sign PDF with not encrypted key in pemder mode

### ISSUE THREAD

**Issue by sl1288** [MatthiasValvekens/pyHanko#87]
**Is your feature request related to a problem? Please describe.**
I have an not encrypted key RSA key and certificate and like to use that in pemder  mode.
It asks for an 'Key passphrase' and returns 'TypeError: Password was given but private key is not encrypted.' if I enter an empty one.

**Describe the solution you'd like**
Add an parameter like "--unencrypted" to skip requesting the 'Key passphrase'

**Comment by MatthiasValvekens** [comment]
That can probably be arranged with minimal effort; I'll take a look in the next few days.

**Comment by MatthiasValvekens** [comment]
I just went ahead and did it, since the change was pretty minimal. :)

This'll be in the next (non-bugfix) release.
